# Import controllers here
from app.controllers.auth_controller import auth_bp
from app.controllers.customer_controller import customer_bp
from app.controllers.raman_controller import raman_bp
from app.controllers.project_controller import project_bp
from app.controllers.optimization_controller import optimization_bp
from app.controllers.api_controller import api_bp
from app.controllers.upload_controller import upload_bp
from app.controllers.query_controller import query_bp
from app.controllers.producer_controller import producer_bp